name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - run: mkdir -p ./src/main/resources
    - run: touch ./src/main/resources/application.properties
    - run: echo "${{ secrets.MAIN_APPLICATION }}" > ./src/main/resources/application.properties
    - run: cat ./src/main/resources/application.properties

    - run: touch ./src/main/resources/application-real1.properties
    - run: echo "${{ secrets.MAIN_APPLICATION_REAL1 }}" > ./src/main/resources/application-real1.properties
    - run: cat ./src/main/resources/application-real1.properties

    - run: touch ./src/main/resources/application-real2.properties
    - run: echo "${{ secrets.MAIN_APPLICATION_REAL2 }}" > ./src/main/resources/application-real2.properties
    - run: cat ./src/main/resources/application-real2.properties

    - run: mkdir -p ./src/test/resources
    - run: touch ./src/test/resources/application.properties
    - run: echo "${{ secrets.TEST_APPLICATION }}" > ./src/test/resources/application.properties
    - run: cat ./src/test/resources/application.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Make zip file
      run: zip -r ./my-delivery-app.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./my-delivery-app.zip s3://my-delivery-app-build/my-delivery-app.zip

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name my-delivery-app \
        --deployment-group-name my-delivery-app \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=my-delivery-app-build,bundleType=zip,key=my-delivery-app.zip \
        --region ${{ secrets.AWS_REGION }}
        
